// Code generated by mockery v2.2.1. DO NOT EDIT.

package statsmocks

import (
	context "context"

	admin "github.com/Yarikf01/graduatedwork/services/admin"

	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetStats provides a mock function with given fields: ctx
func (_m *Manager) GetStats(ctx context.Context) (admin.DataStat, error) {
	ret := _m.Called(ctx)

	var r0 admin.DataStat
	if rf, ok := ret.Get(0).(func(context.Context) admin.DataStat); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(admin.DataStat)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
