// Code generated by mockery v2.2.1. DO NOT EDIT.

package businessmocks

import mock "github.com/stretchr/testify/mock"

// MetricWriter is an autogenerated mock type for the MetricWriter type
type MetricWriter struct {
	mock.Mock
}

// WriteStatPoint provides a mock function with given fields: tags, fields
func (_m *MetricWriter) WriteStatPoint(tags map[string]string, fields map[string]interface{}) {
	_m.Called(tags, fields)
}
