version: "3.2"
services:
  bbwy:
    build:
      context: .
      args:
        - CGO_ENABLED=1
        - BUILD_PARAMS=-a -race
      dockerfile: Dockerfile.bbwy
    ports:
      - "8080:8080"
    environment:
        LOCAL_DEBUG: "true"
        PORT: "8080"
        PROJECT_ID: "bbwy"
